services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_tom
    restart: always
    env_file:
      - ../.env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - tom_network

volumes:
  rabbitmq_data:
    driver: local

networks:
  tom_network:
    name: tom_network
    driver: bridge