import * as process from "node:process";
import dotenv from "dotenv";
dotenv.config();

export const environment = {
	port: parseInt(process.env.PORT ?? "4000"),
	host: process.env.HOST ?? "localhost",
	smtpHost: process.env.SMTP_HOST ?? "",
	smtpPort: parseInt(process.env.SMTP_PORT ?? "587"),
	smtpEmail: process.env.SMTP_EMAIL ?? "",
	smtpPassword: process.env.SMTP_PASSWORD ?? "",
	apiKey: process.env.API_KEY ?? "",
	mongoUrl: process.env.MONGO_URI ?? "",
	bcryptSalt: parseInt(process.env.BCRYPT_SALT ?? "10"),
	tokenSecret: process.env.TOKEN_SECRET ?? "",
	rabbitmqUser: process.env.RABBITMQ_USER ?? "",
	rabbitmqPassword: process.env.RABBITMQ_PASSWORD ?? "",
	rabbitmqHost: process.env.RABBITMQ_HOST ?? "",
	rabbitmqPort: parseInt(process.env.RABBITMQ_PORT ?? "5672"),
	rabbitmqManagementPort: parseInt(process.env.RABBITMQ_MANAGEMENT_PORT ?? "15672"),
	enabledRabbitmq: process.env.ENABLE_RABBITMQ === "true",
	enabledRabbitQueueConsume: process.env.ENABLE_QUEUE_CONSUME === "true",
	rabbitmqVhost: process.env.RABBITMQ_VHOST ?? "",
	uploadServiceType: process.env.UPLOAD_SERVICE_TYPE ?? "IMGUR",
	imgurApiUrl: process.env.IMGUR_API_URL,
	imgurRefreshTokenUrl: process.env.IMGUR_REFRESH_TOKEN_URL,
	imgurAccessToken: process.env.IMGUR_ACCESS_TOKEN,
	imgurRefreshToken: process.env.IMGUR_REFRESH_TOKEN,
	imgurAlbumId: process.env.IMGUR_ALBUM_ID,
	imgurClientId: process.env.IMGUR_CLIENT_ID,
	imgurClientSecret: process.env.IMGUR_CLIENT_SECRET,
	whatsappEnabled: process.env.WHATSAPP_ENABLED === "true",
	nbaApiUrl: process.env.NBA_API_URL,
	nbaApiKey: process.env.NBA_API_KEY,
};